### PR TITLE
Sort videos by views-per-day + download the top ones

### PR DESCRIPTION
**Pull request by deldesir**
🚀 **Pull Request Overview:**

This PR adds views-per-day to the metadata so videos can be sorted automatically based on the playlist. If the playlist contains more than 100, a bookshelf with the top 100 videos (based on their views per day) is created. For playlists with less than 100 videos, the sorting still happens automatically.
Videos are sorted by views-per-day and limited by MAX_VIDEOS_PER_DOWNLOAD

📌 **Testing scenarios:**
See Issue #97 

cc @EMG70

### CODE REVIEW

**Comment by deldesir** [comment]
Test with a channel of 87 videos: https://www.youtube.com/@SpeechBlubs

image

Bookshelf is named after the channel

image

**Comment by holta** [comment]
Which test scenarios (top of #97 or bottom of #97) are most important for @EMG70 & others to confirm here?

**Comment by deldesir** [comment]
I will number them correctly for better communication

**Comment by deldesir** [comment]
> Which test scenarios (top of #97 or bottom of #97) are most important for @EMG70 & others to confirm here?

Test scenario 12: Shelf Title Retrieval (Channel):

**Comment by deldesir** [comment]
Test scenario 6: Valid Download with Progress Observation (Playlist)
Playlist if 156 videos: https://www.youtube.com/playlist?list=PLjxrf2q8roU23XGwz3Km7sQZFTdB996iG

100 top videos downloaded:

image

Shelf named after the playlist title:

image

**Comment by EMG70** [comment]
IIAB-DIAGNOSTICS - http://sprunge.us/oECy1e?en
This playlist https://www.youtube.com/playlist?list=PLGjplNEQ1it_oTvuLRNqXfz_v_0pq6unW of 14 videos was downloaded successfully and videos in order of ranking.. see screenshot.

Subsequent download attempts for these below have all failed in tasks but an empty  bookshelf name is created.
https://www.youtube.com/playlist?list=PLGjplNEQ1it_oTvuLRNqXfz_v_0pq6unW  14 videos
https://www.youtube.com/playlist?list=PLfEr2kn3s-bo4LwlbyZugHPavhcdW8YMC               97 videos 
Screenshot from 2024-03-27 14-51-32
Screenshot from 2024-03-27 14-52-05
Screenshot from 2024-03-27 14-55-11
Screenshot from 2024-03-27 15-03-21

**Comment by EMG70** [comment]
There was a cancelled video download immediately after the successful download.I hope this did not cause problems for the database.I am currently creating a new VM and retest,will update shortly.
Screenshot from 2024-03-27 15-08-42

**Comment by EMG70** [comment]
**UPDATE**
SUDO IIAB-DIAGNOSTICS - http://sprunge.us/XNJk13?en

A new VM was created .The first playlist downloaded OK with ranking showing well.It was observed that only the first playlist downloadS ok and populates videos in the shelf.All further downloads thereafter have been failing together with the previously successful playlist https://www.youtube.com/playlist?list=PLGjplNEQ1it_oTvuLRNqXfz_v_0pq6unW.
Screenshot from 2024-03-27 20-23-56
Screenshot from 2024-03-27 20-24-12
Screenshot from 2024-03-27 20-25-28
**EMPTY SHELVES**
Screenshot from 2024-03-27 20-25-44
Screenshot from 2024-03-27 20-30-39

**Comment by deldesir** [comment]
Thanks @EMG70, I'll fix this issue tonight. #150

**Comment by holta** [comment]
@deldesir clarifies:

"[PR #146] has no diff because [PR #147] merged 4 days ago was built upon it."

"In fact, I resolved a merge conflict in it by adding its original commit, which was already present in [PR #147]."

✅

**Pull request closed without merging**
