### PR TITLE
Log yt-dlp version

### PR DESCRIPTION
**Pull request by deldesir**
Enhance the log by recording the version of the underlying yt-dlp used by xklb.

### CODE REVIEW

**Comment by holta** [comment]
Variables XKLB_EXECUTABLE and YT_DLP_EXECUTABLE add more complexity than genuine value in my own opinion:

1) But either way, if they must be used, avoid dashes (hyphens) in bash variable names:
 
   https://unix.stackexchange.com/questions/23659/can-shell-variable-name-include-a-hyphen-or-dash

2) Please confirm this PR is tested!

**Comment by holta** [comment]
@deldesir: revise/finalize this PR soon if possible?

**Comment by deldesir** [comment]
> Variables XKLB_EXECUTABLE and YT_DLP_EXECUTABLE add more complexity than genuine value in my own opinion:

I removed their assignments since they are not used externally.

**Comment by holta** [comment]
Looks promising!

(Just let @EMG70, I & others know when we can hopefully test soon!)

**Comment by deldesir** [comment]
Tested on ubuntu 24.04

```
root@box:/opt/iiab/iiab# cat /var/log/xklb.log | grep yt-dlp
2024-05-02 16:54:09 - [Info] Using yt-dlp 2024.04.09
2024-05-02 16:54:09 - [Debug] yt-dlp initialized 0.0749
2024-05-02 16:54:13 - [Info] Using yt-dlp 2024.04.09
2024-05-02 16:54:13 - [Debug] {'noprogress': True, 'lazy_playlist': True, 'noplaylist': True, 'no_check_certificate': True, 'ignore_no_formats_error': True, 'skip_playlist_after_errors': 21, 'playlistend': 20000, 'extractor_args': {'youtube': {'skip': ['authcheck']}}, 'logger': <xklb.createdb.tube_backend.download.<locals>.DictLogger object at 0x703f28e6e240>, 'postprocessors': [{'key': 'FFmpegMetadata'}, {'key': 'FFmpegEmbedSubtitle'}], 'restrictfilenames': True, 'playlist_items': '1', 'extractor_retries': 3, 'retries': 12, 'retry_sleep_functions': {'extractor': <function download.<locals>.<lambda> at 0x703f28542160>, 'http': <function download.<locals>.<lambda> at 0x703f28542200>, 'fragment': <function download.<locals>.<lambda> at 0x703f285422a0>}, 'outtmpl': {'default': '/library/downloads/calibre-web/%(extractor_key,extractor)s/%(uploader,uploader_id)s/%(title).200B_%(view_count)3.2D_[%(id).60B].%(ext)s', 'chapter': '/library/downloads/calibre-web/%(extractor_key,extractor)s/%(uploader,uploader_id)s/%(title).200B_%(section_number)03d_%(section_title)s_%(view_count)3.2D_[%(id).60B].%(ext)s'}, 'progress_hooks': [<function download.<locals>.<lambda> at 0x703f28542340>], 'subtitlesformat': 'srt/best', 'format': 'best', 'format_sort': ['tbr~1000'], 'writethumbnail': True, '_warnings': ['"-f best" selects the best pre-merged format which is often not the best option.\n         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.\n         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning']}
```

**Comment by holta** [comment]
@EMG70 can you test a fresh install of IIAB's Calibre-Web if you have a chance, now that this PR #159 is merged?

**Pull request merged**
