### PR TITLE
Read error from xklb-metadata.db [leveraging yt-dlp STDERR]

### PR DESCRIPTION
**Pull request by deldesir**
Instead of reporting the exception as a status message, this PR reads the error from xklb db. This enhances debugging. Exception will still be logged because they're useful to understand errors from calibre-web's context. Reading the error from the database helps understand errors from xklb's context leveraging yt-dlp STDERR.

### CODE REVIEW

**Comment by deldesir** [comment]
[Testing result placeholder]

**Comment by deldesir** [comment]
Retrying to download the failed video still hangs the metadata fetching task despite applying a timestamp. I'll put this PR into draft mode while I am figuring out what's going on.

**Comment by deldesir** [comment]
This PR is ready for merge. It will help better in understanding the underlying causes of failures. Another one will address the hanging at metadata fetch when a retry of a failed video is attempted.

**Comment by holta** [comment]
> > Another one will address the hanging at metadata fetch when a retry of a failed video is attempted.
> 
> @deldesir Clarify when you can? Thank you!

@deldesir are you saying this relates to some or all of the 3 tickets below... ?

- #150
- PR #151
- #153

**Comment by deldesir** [comment]
Yes, but it was affecting single videos. They were mostly unavailable videos, but any video which failed in a previous attempt would fit into this category as well.

**Comment by holta** [comment]
Can #150 and/or #153 be closed soon?

(Or are these not fully solved yet?)

**Pull request merged**
