### PR TITLE
Revert to upload task

### PR DESCRIPTION
**Pull request by deldesir**
🚀 **Pull Request Overview:**

This PR does the following changes:
- Reverts to showing subsequent upload rows for every video dowloaded
- Fixes the bookshelf bug reported in #98 

📋 **Checklist:**
- [x] Tested on Ubuntu 24.04
- [x] Checked for backward compatibility (bookshelf feature)

🔗 Related Issue: #89

📌 **Testing scenarios:**
See Issue #97 

cc @EMG70

### CODE REVIEW

**Comment by holta** [comment]
Looks great.

Please install on LRN2 and support @EMG70 in whatever he needs to understand + test!

**Comment by holta** [comment]
Enumeration of videos in a playlist/channel is important... as @EMG70 also suggested... but probably needs another PR or more!?

 🔢

**Comment by EMG70** [comment]
iiab-diagnostics http://sprunge.us/nvXFiR?en

This PR does the following changes:

    Reverts to showing subsequent upload rows for every video dowloaded ✅
    Fixes the bookshelf bug reported in playlist download will report 500 internal server  ✅
Screenshot from 2024-01-18 13-48-05

**Comment by deldesir** [comment]
Thanks @EMG70 for testing

**Comment by holta** [comment]
> Thanks @EMG70 for testing

✅

Awesome!  And soon:

- Enumeration (numbering) of each video in the playlist/channel, from 1 to 100.
- The word "Upload:" will need to be changed (or just removed?) as it conveys the wrong meaning to implementers.
- Additional "Vitals" about each video... should probably appear in each video's row.  Possibly including (1) HH:MM:SS Duration (2) Date of video publication (3) "Views-per-Day" average popularity, as derived from YouTube.  The list goes on, as Metadata is of course endless in the AI Age.  _But something those ~3 appears quite likely!_

**Pull request merged**
