### PR TITLE
Find thumbnail [restore scan for .webp, .jpg, .png or .gif to support Vimeo etc — not just .webp thumbnails as provided by yt-dlp from YouTube!]

### PR DESCRIPTION
**Pull request by deldesir**
This PR adjusts the thumbnail fetching mechanism based on the assumption its location is inside the video directory.

### CODE REVIEW

**Comment by deldesir** [comment]
Vimeo thumbnails are jpg, we no longer support webp files only

**Comment by holta** [comment]
Look great:

Let's test & merge as soon as PR chapmanjacobd/library#38 or similar is ready!

**Review by holta — APPROVED** [review]

**Comment by holta** [comment]
Awaiting a new version of xklb that includes this commit:

- https://github.com/chapmanjacobd/library/commit/b51300a33d80a81bdeb278687c4eb3cbea152a01

**Comment by holta** [comment]
> Awaiting a new version of xklb that includes this commit:
> 
> * [chapmanjacobd/library@b51300a](https://github.com/chapmanjacobd/library/commit/b51300a33d80a81bdeb278687c4eb3cbea152a01)

CORRECTION!

This PR was tested to work on 10.8.0.62 (24.10) thanks to:

- https://github.com/chapmanjacobd/library/commit/bb97e2401db3477bb76790233e941fb8f60b041e

...as discussed on:

- chapmanjacobd/library#38

**Comment by holta** [comment]
@EMG70 progress report:

- Vimeo thumbnails should be copied correctly into `/library/calibre-web` ✅ 
- Vimeo videos themselves are not being copied correctly at the moment: ❌ 
  - #164

**Comment by EMG70** [comment]
Noted,will await your instructions to test later.

**Comment by holta** [comment]
> Noted,will await your instructions to test later.

Three PRs were just merged (PR140, PR162, PR163) — that's 99 PR's in total, that are now merged. 🌱

@deldesir should confirm ASAP which/other PRs are "rock solid" / tested / ready:

https://github.com/iiab/calibre-web/pulls

**Comment by holta** [comment]
Docs revised:

- https://github.com/iiab/calibre-web/commit/63ff431a002f1615296a3295e602a2a189a41a9f
- https://github.com/iiab/calibre-web/wiki#dont-judge-a-book-by-its-cover

**Pull request merged**
