### PR TITLE
Select the requested failed URL instead of the first one encountered 

### PR DESCRIPTION
**Pull request by deldesir**
🚀 **Pull Request Overview:**

This PR displays the Total Duration of videos requested in the "metadata fetch" task.

📋 **Checklist:**
- [x] Tested the changes on Ubuntu 24.04

Related Issue: #129 

total_duration

### CODE REVIEW

**Comment by holta** [comment]
Is this PR displaying intended playback duration?

Of playlists only?

> What about displaying the bookshelf title as well, If a playlist URL is submitted?

Feel free to propose a screenshot visual?

(If "Tasks" view remains very succinct?)

**Comment by holta** [comment]
I do not understand what is happening when statements are made without context:

- "Video 2/2"

- "Total Duration: 0:16:32"

Precise explanations need to explain exactly what is happening.

(Or, confusing distractions need to be fully removed.)

**Comment by holta** [comment]
Language like "Metadata Fetch: Successfully fetched metadata for" is (1) repetitive and (2) does not tell me what is happening and why.

(A clear explanation would tell me where metadata is coming FROM, and where metadata is going TO.)

**Comment by deldesir** [comment]
> Is this PR displaying intended playback duration?

Yes. The value is retrieved from xklb-metadata and converted from seconds to HH:MM:SS

> Of playlists only?

Duration of single video works as well

> What about displaying the bookshelf title as well, If a playlist URL is submitted?
> Feel free to propose a screenshot visual?
> 
> (If "Tasks" view remains very succinct?)

Noted. But I am afraid that won't be much useful if the playlist has many videos. I noticed the first task is pushed up (without any possiblity to see it again) when many videos are being downloaded.

**Comment by deldesir** [comment]
> Language like "Metadata Fetch: Successfully fetched metadata for" is (1) repetitive and (2) does not tell me what is happening and why.

Yes, a better status message or/an task name is required ASAP.

> (A clear explanation would tell me where metadata is coming FROM, and where metadata is going TO.)

This PR started as refactor to display duration and number of videos to be displayed but ended up as a fix to #129.

What changed?
When a video is requested and no metadata is returned from YouTube, an error is recorded in the database for the URL. This error is taken into consideration by the download task which discards thd URL automatically. This mechanism was bogus and only the first error encountered was being returned before this PR. This caused the number videos to be downloaded to increase, including a previous failed URL (the first one encountered). This affected the progress which is calculated as follows: index number of the video / total number of videos.

**Comment by holta** [comment]
@deldesir what's your recommendation to tighten up here l?

Or perhaps better in a follow-up PR?

**Comment by deldesir** [comment]
I recommend to merge this PR as it fixes #129. I am waiting for Ed feedback and some suggestions regarding the wording of the task message. Your suggestions are welcome.

**Comment by deldesir** [comment]
As for an eventual follow up PR, the view_count metadata will be used as the basis to get the top 100 videos in any playlist. The resulted/derived bookshelf should contain videos based on this criterion although they will appear unordered in the shelf view, but we are covered by the bookshelf filtering buttons. One that will be useful is the "arrange by pubdate" button.

**Comment by holta** [comment]
Is "Video 2/2" supposed to be an animation?

That changes from "Video 0/2" to "Video 1/2" to "Video 2/2" for a playlist of 2 videos?

Or some other goal?  (Goal needs to be crystal clear, with an illustrative screenshot, or video screen capture if animation is absolutely necessary.)

> In this PR, the duration metadata is coming from reading xklb-metadata.db to be displayed in metadata Task 's message (not really useful IMHO as it ends up buried when we have more than 30 videos in download queue.

Please provide screenshot(s).

Show exactly what you mean by "buried".

(And why others should tolerate this?)

**Comment by deldesir** [comment]
> Is "Video 2/2" supposed to be an animation?

It is (but it's too fast)

> That changes from "Video 0/2" to "Video 1/2" to "Video 2/2" for a playlist of 2 videos?
> 
> Or some other goal? (Goal needs to be crystal clear, with an illustrative screenshot, or video screen capture if animation is absolutely necessary.)

Yes, the goal is to change the message on each iteration of adding the tasks to the queue
 
> > In this PR, the duration metadata is coming from reading xklb-metadata.db to be displayed in metadata Task 's message (not really useful IMHO as it ends up buried when we have more than 30 videos in download queue.
> 
> Please provide screenshot(s).

Here is what we have when we submit this URL https://www.youtube.com/playlist?list=PLU6sEQK7ize-4xjVnhQhgDQVcRaHO_y8p


> Show exactly what you mean by "buried".

Notice the first row 2 minutes later
https://www.youtube.com/playlist?list=PLU6sEQK7ize-4xjVnhQhgDQVcRaHO_y8p
 
> (And why others should tolerate this?)
I didn't say we should tolerate this. If this needs a fix, I'll dedicate some time to understand it.

**Comment by holta** [comment]
@deldesir thanks for the explanations! 👍

QUESTION: When the 1st row (of "Tasks" view) is no longer visible in browser — as if that line has scrolled off the top — is the data still available to be viewed if you open the same page with a much larger browser on a much larger screen?

**Comment by deldesir** [comment]
> @deldesir thanks for the explanations! 👍
> 
> QUESTION: When the 1st row (of "Tasks" view) is no longer visible in browser — as if that line has scrolled off the top — is the data still available to be viewed if you open the same page with a much larger browser on a much larger screen?

Answered in #132: TASK_CLEANUP_TRIGGER must be increased to make the data viewable.

**Comment by deldesir** [comment]
Does the message/wording looks improved to you @holta (first row)?
cropped

**Comment by holta** [comment]
Thanks @EMG70 for having tested this:

- It's not clear that 2s and 3s "Run Times" in the screenshots below are accurate or meaningful.
- "Task" view "animations" create serious UX problems.
  - Animation needs to be **avoided** as a general rule — driving focus for "Tasks" view needs to be clean **copy/pasting without bells & whistles.**
  - Avoid complexity and its inevitable maintenance burdens!
  - Nevertheless: We will tolerate this exception (e.g. "Number of Videos: 35/35" animation) for now.

IMG-20240220-WA0001
IMG-20240220-WA0002

**Pull request merged**
