### PR TITLE
scripts/lb-wrapper: Try yt-dlp with "--format best --format-sort 'tbr~1000'" [testing shows need for URL validation, clearly communicated, for users who accidentally request the impossible after clicking "Download to IIAB" > "Start"]

### PR DESCRIPTION
**Pull request by holta**
@deldesir @EMG70 please consider testing this alternative alongside:

- PR #60
- PR #62

### CODE REVIEW

**Comment by holta** [comment]
> @deldesir @EMG70 please consider testing this alternative alongside:

Start by testing these same 4 URL's ?

- https://github.com/iiab/calibre-web/pull/62#issuecomment-1847269641

**Comment by holta** [comment]
@EMG70 explanation is emerging at:

- "Tweaking Video Quality"
https://github.com/iiab/calibre-web/wiki#tweaking-video-quality

(If this explanation contains shortcomings, please shout with your suggestions!)

**Comment by EMG70** [comment]
Latest test
Screenshot from 2023-12-09 09-58-50
Screenshot from 2023-12-09 10-05-58

**Comment by EMG70** [comment]
Screenshot from 2023-12-09 10-12-23

**Comment by EMG70** [comment]
Screenshot from 2023-12-09 11-13-54

**Comment by holta** [comment]
Results with...

Binary Search Algorithm in 100 Seconds
https://www.youtube.com/watch?v=MFhxShGxHWc

IMG-20231209-WA0007~3

**Comment by EMG70** [comment]
4 Things all great listeners know-Ted Ed
Screenshot from 2023-12-09 11-25-14

**Comment by EMG70** [comment]
Successful download of mp4 video but server crushed after refreshing.(502 Bad gateway)
Screenshot from 2023-12-09 14-00-35
Screenshot from 2023-12-09 13-58-14
Screenshot from 2023-12-09 13-56-40
Screenshot from 2023-12-09 13-56-22
Screenshot from 2023-12-09 13-56-02
Screenshot from 2023-12-09 13-54-37
Screenshot from 2023-12-09 13-54-22
Screenshot from 2023-12-07 19-56-59

**Comment by EMG70** [comment]
Screenshot from 2023-12-09 14-06-08

**Comment by EMG70** [comment]
Screenshot from 2023-12-09 14-09-28

**Comment by EMG70** [comment]
Screenshot from 2023-12-09 15-22-34
Screenshot from 2023-12-09 15-21-37
Screenshot from 2023-12-09 15-21-09
Screenshot from 2023-12-09 14-20-49

**Comment by EMG70** [comment]
Screenshot from 2023-12-09 15-27-14

**Comment by EMG70** [comment]
Screenshot from 2023-12-09 15-32-26

**Comment by EMG70** [comment]
pastebinit -b sprunge.us//var/log/xklb.log
http://sprunge.us/BT3ZHs?en

pastebinit -b sprunge.us/var/log/calibre-web.log
http://sprunge.us/ohha35?en

**Comment by holta** [comment]
> pastebinit -b sprunge.us//var/log/xklb.log
> http://sprunge.us/BT3ZHs?en

@deldesir can you help us understand why Line 86 is very different from the others?

> 86 2023-12-09 13:49:03 - Running command: lb tubeadd /library/downloads/calibre-web/survey.db https://yt-dlp --format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" https://www.youtube.com/watch?v=sOE8Slo3Pqw" --verbose && lb dl /library/downloads/calibre-web/survey.db --prefix /library/downloads/calibre-web --write-thumbnail -f best -S 'tbr~1000' --video https://yt-dlp --format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" https://www.youtube.com/watch?v=sOE8Slo3Pqw" --verbose

**Comment by EMG70** [comment]
> > pastebinit -b sprunge.us//var/log/xklb.log
> > http://sprunge.us/BT3ZHs?en
> 
> @deldesir can you help us understand why Line 86 is very different from the others?
> 
> > 86 2023-12-09 13:49:03 - Running command: lb tubeadd /library/downloads/calibre-web/survey.db https://yt-dlp --format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" https://www.youtube.com/watch?v=sOE8Slo3Pqw" --verbose && lb dl /library/downloads/calibre-web/survey.db --prefix /library/downloads/calibre-web --write-thumbnail -f best -S 'tbr~1000' --video https://yt-dlp --format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" https://www.youtube.com/watch?v=sOE8Slo3Pqw" --verbose

CLARIFICATION****
Could Line 86 be a result of my error?I copied the following url from my Mp4 downloads yt-dlp -f “bestvideo[ext=mp4]+bestaudio[ext=m4a]” "https://www.youtube.com/watch?v=1xhlg9WkPQg."
I initially forgot to strip the yt-dlp prefix in calibre Download.This download however failed.I then noticed the error and stripped it correctly as and downloaded successfully as mp4 on Calibre.Apologies.

I thought the link was corrupted so tried another one [yt-dlp](https://yt-dlp/) --format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" https://www.youtube.com/watch?v=sOE8Slo3Pqw"
I realized this was 3.5hr video and immediately cancelled in Tasks.
Apologies for sending you on a wild chase but result was successful mp4 download 2min video though system later crushed after playing the video and could not refresh .

**Comment by holta** [comment]
Thanks @EMG70 for clarifying:

@deldesir can we learn anything from this?

(ASIDE: Certainly we need much stronger URL validation — when people click on "Download to IIAB" — so the front-end makes 100% clear telling them exactly what the back-end is and is not capable of, based on the URL they requested!)

**Comment by holta** [comment]
@EMG70 advised me to go ahead and merge this after his extensive testing today:

Huge Thanks to him for his very hard work, confirming this PR is generally very solid i.e. an earnest real step forward helping schools/parents/kids getting the very manageable/tolerable codecs they need in offline and low-income communities!

**Pull request merged**
