### PR TITLE
Safer lb-wrapper: Wrap lb parameters (bash vars) in single quotes

### PR DESCRIPTION
**Pull request by holta**
@deldesir does this work?  Safe enough for now?

(Per @codewiz recommendation.)

### CODE REVIEW

**Comment by deldesir** [comment]
[Testing...]

**Comment by codewiz** [comment]
Looks good to me now.

**Review by deldesir — APPROVED** [review]
Works as expected for me now. I tested it on Ubuntu 24.04.

**Comment by holta** [comment]
> I got this error message:

Apologies.  Is this fixed PR now good enough?

**Pull request merged**
