### PR TITLE
Update helper.py [fixes "SyntaxWarning: invalid escape sequence" in log file]

### PR DESCRIPTION
**Pull request by jvonau**
fixes  "SyntaxWarning: invalid escape sequence"  in log file

### CODE REVIEW

**Comment by holta** [comment]
Thanks @jvonau

@deldesir can you please review today?

**Review by deldesir — APPROVED** [review]
Looks good to me.

**Comment by holta** [comment]
Very awesome:

@jvonau what is your preference: should we merge this or better to get upstream to merge this instead?  @ozzieisaacs is an incredible contributor to humanitarians/users worldwide, so I believe he'd very likely be happy to accept your bugfix PR.

**Comment by jvonau** [comment]
Feel free to summit this on my behalf, I really don't have the time to devote to this.

**Comment by OzzieIsaacs** [comment]
I can't reproduce the error message with my Linux Mint 21.3, but I did a change similar to the suggested one. So I guess the message should now disappear

**Comment by holta** [comment]
Thanks @OzzieIsaacs — your patch looks right on here:

- https://github.com/janeczku/calibre-web/commit/fcc95bd8953c0b1c00c7af1dfd2f3bb3b3c9dbd0

**Comment by holta** [comment]
> Thanks @OzzieIsaacs — your patch looks right on here:
> 
> * [janeczku@fcc95bd](https://github.com/janeczku/calibre-web/commit/fcc95bd8953c0b1c00c7af1dfd2f3bb3b3c9dbd0)

Looks good, thanks to @jvonau and @OzzieIsaacs !

**Pull request closed without merging**
