### PR TITLE
Remove original file

### PR DESCRIPTION
**Pull request by deldesir**
Remove the original downloaded file once it's moved to the library directory.

### CODE REVIEW

**Comment by holta** [comment]
> Remove the original downloaded file once it's moved to the library directory.

This PR appears to mitigate the long-term disk bloat problem, which is great.

Larger Question Equally Important, looking forward:

- Can we try hard to find an `xklb` workflow that _avoids all duplicate video/media files,_ in the 1st place?

- As video files can be Massive: our goal should be to avoid all duplication or copying of such files.

_Reason: Unnecessary duplicates / Unnecessary copying of massive files can dramatically inflate Raspberry Pi CPU/system usage, permanently induce "disk wear" on microSD cards (reducing their operational lifetime), and potentially waste other bandwidth-like resources as well._

**Comment by holta** [comment]
> find an `xklb` workflow that avoids all duplicate video/media files

Is [xklb 2.2.156](https://github.com/chapmanjacobd/library/releases/tag/v2.2.156)'s `lb siteadd` command relevant?  Or a similar xklb command possibly?
```
    $ library siteadd -h
    usage: library site-add DATABASE PATH ... [--auto-pager] [--poke] [--local-html] [--file FILE]

    Extract data from website requests to a database

        library siteadd jobs.st.db --poke https://hk.jobsdb.com/hk/search-jobs/python/

    Run with `-vv` to see and interact with the browser
```

https://github.com/chapmanjacobd/library/blob/492e2e9703ddac04f7e6521cb768f0697573b753/.github/README.md?plain=1#L540-L547

**Comment by holta** [comment]
> > find an `xklb` workflow that avoids all duplicate video/media files
> 
> Is [xklb 2.2.156](https://github.com/chapmanjacobd/library/releases/tag/v2.2.156)'s `lb siteadd` command relevant? Or a similar xklb command possibly?

FWIW newer [xklb 2.2.165](https://github.com/chapmanjacobd/library/releases/tag/v2.2.165) is now available ✅

**Comment by deldesir** [comment]
For now, only the `lb dl` command is relevant. It allows downloading files to a specific location. The only caveat is that xklb does not follow the same download structure as Calibre-Web. Both also name files differently.

**Comment by holta** [comment]
> For now, only the `lb dl` command is relevant. It allows downloading files to a specific location. The only caveat is that xklb does not follow the same download structure as Calibre-Web. Both also name files differently.

Is this perhaps solvable now?  Thanks to:

- chapmanjacobd/library#21
- https://github.com/chapmanjacobd/library/releases/tag/v2.2.167
  - https://github.com/chapmanjacobd/library/commit/9c900b46aae186379f85d234a92145871a9790aa

**Comment by holta** [comment]
This PR does not address the actual problem.

As explained on #45 unnecessary copying is damaging to SD cards.

The solution is _moving not copying_ as explained here:

- https://github.com/iiab/calibre-web/issues/45#issuecomment-1813592789

**Pull request closed without merging**
