### PR TITLE
Escape quotes to fix SyntaxError for RPI

### PR DESCRIPTION
**Pull request by deldesir**
Fixes SyntaxError mentioned in #187. 

Not tested yet. @Nzola can you give this PR a try?

### CODE REVIEW

**Comment by holta** [comment]
@EMG70 would you have time to try this PR?

On any RPi 4 or RPi 400, if so!

Instructions:

https://github.com/iiab/calibre-web/wiki#how-do-i-test-a-pull-request-pr-

**Comment by EMG70** [comment]
> @EMG70 would you have time to try this PR?
> 
> On any RPi 4 or RPi 400, if so!
> 
> Instructions:
> 
> https://github.com/iiab/calibre-web/wiki#how-do-i-test-a-pull-request-pr-

I will try shortly and update you.

**Comment by EMG70** [comment]
SUDO IIAB DIAGNOSTICS - https://dpaste.com/96JFWQJUU
I tested after running PR#201 script and got 502 Bad Gateway
20240624_10h40m35s_grim

**Comment by deldesir** [comment]
Today I learned. Thanks @EMG70. I see what's happening. Next commit will remove the problematic f-string.

**Comment by holta** [comment]
> Today I learned. Thanks @EMG70. I see what's happening. Next commit will remove the problematic f-string.

- Smoke-tested on Ubuntu 24.04
- PR will now be merged
- Needs additional testing after it's merged: can @nzola or @EMG70 fully retest (either fresh install or upgrade on Raspberry Pi!) in the coming 24h ideally?!

**Comment by holta** [comment]
I personally can't reproduce @EMG70's failure of pipx to install xklb on "Raspberry Pi OS with desktop" — based on Debian 12 "Bookworm" — this all works for me:

```
sudo -i
apt install pipx
pipx install xklb

.local/bin/lb --version
.local/pipx/venvs/xklb/bin/yt-dlp --version
pipx upgrade --include-injected xklb
```

@EMG70 can you try the above commands on a completely fresh / untouched install of Raspberry Pi OS ("Lite" version or "with desktop" version) ?

**Comment by EMG70** [comment]
A new small size IIAB was installed .
SUDO IIAB-DIAGNOSTICS - https://dpaste.com/E89S7DXN5
IMG_3881

**Comment by holta** [comment]
@EMG70 looks much better:

Try the "Download to IIAB" button, and let us know how it works!?

**Comment by EMG70** [comment]
SUDO IIAB-DIAGNOSTICS - https://dpaste.com/64GKBP2GX

Download to IIAB working Ok.
Screenshot 2024-06-24 at 22-47-03 Internet in a Box Tasks

**Comment by holta** [comment]
Incredible news, thank you @EMG70 !

**Comment by nzola** [comment]
@deldesir Just to confirm, YES! Calibre-Web is working on both Pi4 and Pi400. Video downloads are working as well without any problems. BIG thank you! @deldesir 
This is for pi4 PUBLISHING TO URL... https://dpaste.com/CQWNGR8BQ

**Comment by deldesir** [comment]
Thanks @nzola for your feedback. Your testing is valuable.

**Pull request merged**
