### PR TITLE
Pin max format [Set 720p 30FPS WebM as the maximum to be downloaded to IIAB, for now?]

### PR DESCRIPTION
**Pull request by deldesir**
Sets the format option to select the best video stream with a height less than or equal to 720 pixels and the best audio stream.

### CODE REVIEW

**Comment by deldesir** [comment]
For now, this will prevent the download of excessively large videos while we work on a fix for issue #37.

**Comment by holta** [comment]
This looks awesome!

If tested, it should be merged promptly to allow for even wider testing.

Questions:

- What happens when an online video (that school/implementer is trying to download to IIAB) offers **only** 1080p or similar, e.g. very higher-resolution heavyweight files?

- How often does the above "bloated video file" situation typically happen?

- Should IIAB perhaps tolerate overweight video files for now — when the source internet website regrettably does not offer more lightweight options — _even if this creates a flood of **very painful complications** for schools and students down the road?_

**Comment by holta** [comment]
> * What happens when an online video (that school/implementer is trying to download to IIAB) offers **only** 1080p or similar, e.g. very high-resolution heavyweight files?

GOAL: Essentially "all" videos should be reliably downloadable to IIAB — even if worst case a gigantic 1080p (or some other overweight format/codec?) is the only file type that its host website is making available! 🚛

**Comment by holta** [comment]
> Sets the format option to select the best video stream with a height less than or equal to 720 pixels and the best audio stream.

@deldesir please spell out assumptions — so I and others can try to understand this PR — Thanks!

1) How commonly is <= 720p available from host websites like YouTube?

2) What happens when <= 720p is NOT available from host websites like YouTube?

3) How do we safely achieve the higher-level goal below?  (In a future-proof manner if possible?!)

> GOAL: Essentially "all" videos should be reliably downloadable to IIAB — even if worst case a gigantic 1080p (or some other overweight format/codec?) is the only file type that its host website is making available! 🚛

**Comment by holta** [comment]
> 1. How commonly is <= 720p available from host websites like YouTube?

1.1 If many different 720p offerings are available (e.g. 8 below) which *should* be chosen?

1.2 Which *is* chosen, with this PR?

Example:

```
# ./yt-dlp --list-formats https://youtu.be/sqoOzGMqCQU
...
[info] Available formats for sqoOzGMqCQU:
ID  EXT   RESOLUTION FPS CH │   FILESIZE    TBR PROTO │ VCODEC      VBR ACODEC      ABR ASR MORE INFO
...
22  mp4   1280x720    30  2 | ≈369.44MiB  2124k https | avc1.64001F          mp4a.40.2       44k [en] 720p
136 mp4   1280x720    30    |  338.84MiB  1995k https | avc1.4d401f    1995k video only          720p, mp4_dash
247 webm  1280x720    30    |  177.31MiB  1044k https | vp9            1044k video only          720p, webm_dash
398 mp4   1280x720    60    |  335.07MiB  1973k https | av01.0.08M.08  1973k video only          720p60, mp4_dash
311 mp4   1280x720    60    | ~841.22MiB  4836k m3u8  | avc1.4D4020    4836k video only
298 mp4   1280x720    60    |  553.50MiB  3259k https | avc1.4D4020    3259k video only          720p60, mp4_dash
612 mp4   1280x720    60    | ~682.13MiB  3921k m3u8  | vp09.00.40.08  3921k video only
302 webm  1280x720    60    |  354.08MiB  2085k https | vp09.00.40.08  2085k video only          720p60, webm_dash

**Comment by deldesir** [comment]
In this PR, we choose the best video stream. We can adjust it to include the best audio stream as well like https://github.com/openzim/youtube/blob/daf348c5421427f47550b8575841426a32926a7a/src/youtube2zim/scraper.py#L534

**Comment by holta** [comment]
> In this PR, we choose the best video stream.

What is meant by "best" ?  (Do you mean "largest" video file that <= 720p ?)

The [table above](https://github.com/iiab/calibre-web/pull/48#issuecomment-1824686726) shows some 720p files are almost 5X larger than others.  That doesn't mean they have better resolution or better overall playback quality, e.g. if MP4 doesn't compress as well as WebM:

- Should we perhaps mandate a preference WebM instead of MP4 by default?

- Should we perhaps mandate a preference for 30FPS over 60FPS by default?

- Regardless, can we guarantee a video is downloaded in almost all cases?  (Even if it's a poorly compressed 1080p in isolated/unfortunate corner cases!)

**Comment by deldesir** [comment]
Here is an excellent answer from @pukkandan explaining yt-dlp's criterion for "best" video and audio which appears to be the largest bitrate:  https://www.reddit.com/r/youtubedl/comments/oikhiu/does_f_bestvideobestaudio_on_ytdlp_actually_give/

What's positive, if we don't set yt-dlp to pick a specific format, we have the guarantee a video will always be downloaded. I recommend however to prefer webm 720p resolution (30fps) to avoid the largest video from being downloaded.

**Comment by holta** [comment]
@deldesir can you download and watch this 1044 Mbit/sec file (177.31MiB) to confirm quality is fully good enough?

```
# ./yt-dlp --list-formats https://youtu.be/sqoOzGMqCQU
...
[info] Available formats for sqoOzGMqCQU:
ID  EXT   RESOLUTION FPS CH │   FILESIZE    TBR PROTO │ VCODEC      VBR ACODEC      ABR ASR MORE INFO
...
247 webm  1280x720    30    |  177.31MiB  1044k https | vp9            1044k video only          720p, webm_dash

**Comment by holta** [comment]
> @deldesir can you download and watch this 1044 kbit/sec file (177.31MiB over 23min44sec) to confirm quality is fully good enough?

Please also help determine if similar 30FPS 720p WebM is similarly tight for fine writing on blackboards/whiteboards?

_(Even if file's "viewing code" is rather higher than 1Mbit/sec in the end ??!)_

**Comment by holta** [comment]
This PR needs to work well — but does not need to be perfect, as it will surely evolve later — as low-income schools make more clear their true needs!

Still, let's do our best to document out assumptions/approach as of November 2023.  So this ticket can be re-read and understood later when that's needed ✅

**Comment by chapmanjacobd** [comment]
It might be good to sort more than filter as mentioned here: https://github.com/yt-dlp/yt-dlp/issues/5169

**Comment by holta** [comment]
Awesome step forward!!  That will surely evolve more later, Really Great News ✅

**Pull request merged**
