### PR TITLE
Add --live flag to support downloading of "live" videos

### PR DESCRIPTION
**Pull request by deldesir**
This PR introduces `--live` so live videos can be downloaded. It was tested with a fork of xklb with the changes proposed in https://github.com/chapmanjacobd/library/pull/41

image

### CODE REVIEW

**Comment by holta** [comment]
There needs to be a deeper discussion about what "live" YouTube videos really mean.

Forthrightly acknowledging the differences between "actually live" YouTube videos and "formerly live" YouTube videos (and the dramatically consequences realities of downloading both kinds) will the design process to move forward with sincere respect for all people involved.

Please help articulate what's really needed in the design discussion here:

- https://github.com/iiab/calibre-web/issues/188#issuecomment-2188818111

**Comment by holta** [comment]
Looks good!

Please test with all 3+ kinds of "ostensibly live" YouTube videos: (and please explain what happens in each case)

1. Not Yet Live
2. Actually Live
3. Formerly Live

Actual test cases are posted here, to help with testing:

- https://github.com/iiab/calibre-web/issues/188#issuecomment-2190399720

**Comment by holta** [comment]
> Please test with all 3+ kinds of "ostensibly live" YouTube videos: (and please explain what happens in each case)
>
> 1. Not Yet Live
> 2. Actually Live
> 3. Formerly Live

RECAP: To help push this PR forward, please take very seriously all 3 kinds of test cases outlined at...

- https://github.com/iiab/calibre-web/issues/188#issuecomment-2184046657

**Comment by deldesir** [comment]
Not Yet Live

Actually Live

3. Formerly live: https://www.youtube.com/watch?v=tvMkRUmAD_k&pp=ygUGc3RyZWFt
image

**Comment by deldesir** [comment]
Regression / Known issue (introduced by this PR):

"Upcoming live" and "Actually live" videos are caught in subsequent downloads as requested videos. They will remain as such until they are available, that means having a duration value.

image

**Comment by holta** [comment]
> "Upcoming live" and "Actually live" videos are caught in subsequent downloads as requested videos. They will remain as such until they are available, that means having a duration value.

Thanks @deldesir for explaining, alongside:

- Vital screenshots above, making clear our 3 primary cases
- xklb-metadata.db's corresponding `live_status` values {`is_upcoming`, `is_live`, `was_live`}

Follow-up PR will clean up and clarify very soon, as outlined here:

- https://github.com/iiab/calibre-web/issues/202

**Pull request merged**
