### PR TITLE
Crop covers upon uploading media [using smartcrop, if its bugginess can be fully contained?]

### PR DESCRIPTION
**Pull request by deldesir**
Automatically crop the cover when a video or photo is uploaded.

### CODE REVIEW

**Comment by holta** [comment]
Personally I'm at not thrilled with smartcrop's bugginess, includes issue 21 below and possibly others?

- deldesir/calibre-web#19
- deldesir/calibre-web#21
- deldesir/calibre-web#22

"Dead Simple" cropping based on centering (or no cropping at all) might be better?

But if @thadk and/or @deldesir offer a guarantee that this rabbit hole of complexity/bugginess can be fully contained, I'm definitely willing to listen!

**Comment by thadk** [comment]
Sorry, I didn't mean to endorse any particular library: I was mostly just pointing out there was an underlying technique to focus images better. Also I haven't looked into them at all and there could be a difference between the JS and Python implementations.

**Comment by holta** [comment]
Overnight Summary/Recap thanks to @deldesir:

- Installing smartcrop within Ubuntu 23.10 venv (/usr/local/calibre-web-py3) was not enough 😢
- Theory: Possibly smartcrop itself is not yet ready for the Python 3.11 with PEP 668 venv's (or some such!)
- PRELIMINARY CONCLUSION: Let’s avoid smartcrop for now.

**Comment by holta** [comment]
Should this PR be closed?

Or is there a chance it will be reworked — with or without smartcrop?
(The 3 files' merge conflicts can easily be resolved, if that proves necessary.)

**Pull request closed without merging**
