### PR TITLE
Ignore failed/residual/stuck video downloads: download only newly requested one(s)

### PR DESCRIPTION
**Pull request by deldesir**

### CODE REVIEW

**Comment by holta** [comment]
What is meant by "trailing videos" ?

(Thanks for explaining!)

**Comment by deldesir** [comment]
Videos from a another session which was not downloaded or failed for some reason. It might be leftover videos resulting from testing lb-wrapper or a from a parallel downloading in case of a multi-user usecase.

**Comment by holta** [comment]
Is the new subject line tolerable?

(Improve on it if nec!)

**Comment by deldesir** [comment]
It's better

**Comment by holta** [comment]
Is this PR tested?

Is this PR closely related to... ?

- PR #146 
- #150

**Comment by deldesir** [comment]
It's being tested right now.
> Is this PR closely related to... ?
> 
> * PR [Sort videos by views-per-day + download the top ones #146](https://github.com/iiab/calibre-web/pull/146)
> * [Subsequent [playlists] downloads fail #150](https://github.com/iiab/calibre-web/issues/150)

Yes. Additionally, xklb considers the playlist already downloaded, same issue we encountered when redownloading single videos. I will address this with a similar fix, adding a timestamp to every playlist downloaded. I have yet to test a channel to check for this behavior.

**Comment by deldesir** [comment]
Tested with #151. Ready for merge.

**Comment by holta** [comment]
Should this be merged now?

Or better to wait a bit?

**Review by deldesir — COMMENTED** [review]
Yes. This works good enough.

**Pull request merged**
