### PR TITLE
Add download task

### PR DESCRIPTION
**Pull request by deldesir**
Add "download" to the current job queue mechanism to better handle and prioritize download-related tasks

### CODE REVIEW

**Comment by holta** [comment]
Does this implement... ?

- #8

What testing is most needed before &/or after merging?

**Comment by deldesir** [comment]
Yes

> Does this implement... ?

Yes, the code is consistent with the subprocess wrapper. Some adjustments pertaining to metadata extraction code is necessary before merging this. As usual, this will need to be battle-tested after merging :-)

**Comment by holta** [comment]
"TO DO"

- More Testing
- Data performance
- Align w/ IIAB directory structures

**Comment by deldesir** [comment]
IIAB directory structure alignement will be shipped in it own PR

**Pull request merged**
