### PR TITLE
Download a single video instead of all videos in a playlist

### PR DESCRIPTION
**Pull request by deldesir**
🚀 **Pull Request Overview:**

This PR ensures a single video is downloaded using its relevant url from all those added to the database by `lb tubeadd`

📋 **Checklist:**
- [x] Tested the changes on Ubuntu 24.04

:bug:  **Related issue(s)**: #114, #120

📌 **Testing scenarios:**
- Submit a valid playlist URL
- Observe the sequential progress polling for each download
- Observe accurate runtime (not 0s) in Runtime column
- Observe the successful downloads of all videos

Screenshot_20240209-080523

cc @EMG70

### CODE REVIEW

**Comment by EMG70** [comment]
Test PR#124
IIAB-DIAGNOSTICS http://sprunge.us/cPanTU?en
Submit a valid playlist  - URL https://www.youtube.com/playlist?list=PL0o_zxa4K1BXr49VZTEyUS5-G8fz0Pt1v  ✅

Observe the sequential progress polling for each download ✅
This playlist showed as failed on first top row but sequential progress polling OK as dscribed by @deldesir .All videos downloaded despite failed state at top row.
Screenshot from 2024-02-09 22-56-44
Another test was tried with a different playlist url  - https://www.youtube.com/playlist?list=PLqxP5EuGxPneuoIZWovAfOXUVlvlv3SSM,all downloaded without issues.see below.
Screenshot from 2024-02-09 22-57-53

Observe accurate runtime (not 0s) in Runtime column ✅

**Comment by EMG70** [comment]
A second attempt to download previously failed status url https://www.youtube.com/playlist?list=PL0o_zxa4K1BXr49VZTEyUS5-G8fz0Pt1v resulted in a warning about members only video ..Which I think is not correct output.
Screenshot from 2024-02-09 23-26-10

**Comment by deldesir** [comment]
I can't find the failed video among the 11 ones which are in the Playlist. Could it be hidden? I don't have an answer now. 

Here is the URL of the failed video for context:
https://m.youtube.com/watch?v=JufLGbcXXjY

**Comment by EMG70** [comment]
The perceived failed message was not a failure to download any part of playlist but just the displayed output at initial download instance (row 1 of first screenshot),the message comes up as failed Task progress should be within range [0,1] see first screenshot.
The url was https://www.youtube.com/playlist?list=PL0o_zxa4K1BXr49VZTEyUS5-G8fz0Pt1v

**Pull request merged**
