### PR TITLE
Add upstream commits

### PR DESCRIPTION
**Pull request by deldesir**
The merge conflicts are resolved. All the commits from upstream can be merged with this PR. Will give a quick feedback soon once I am done testing it.

### CODE REVIEW

**Comment by holta** [comment]
> The merge conflicts are resolved. All the commits from upstream can be merged with this PR. Will give a quick feedback soon once I am done testing it.

@EMG70 this PR #128 is probably equivalent to a more clean/transparent way forward.

Just FYI not the end of the world today, but in future @deldesir and everyone should avoid silent code commits like these below...

- https://github.com/iiab/calibre-web/commit/7e69222d76b0e6a3d974d0354974befd50cea8e1 "Sync with upstream" (1:18pm EST)
- https://github.com/iiab/calibre-web/commit/a8d4dc4d6abdb9e4072f2cad931d2c2f9c355b08 "Add missing imports" (1:15pm EST)
- https://github.com/iiab/calibre-web/commit/0b93e0d282f3ffdd8ef59a247609a68f92516d6a "Sync with upstream" (1:04pm EST)

...documentation commits directly to main/master branch are a great thing, when they shine a light for everyone and cut through bureaucracy to deliver that.  (Conversely, code commits always belong in PR's!)

**Comment by holta** [comment]
> The merge conflicts are resolved. All the commits from upstream can be merged with this PR. Will give a quick feedback soon once I am done testing it.

What's the status?

(For @EMG70 and @Nzola especially, Thanks @deldesir!)

**Comment by deldesir** [comment]
Works as expected on 10.8.0.26 (Ubuntu 24.04) for both video URL and playlist URL.

Screenshot_20240215-201851


Screenshot_20240215-201919

**Comment by nzola** [comment]
> Member

I just was busy today. I will test with LRS2.org, Multipass and iiab at midnight.

**Comment by holta** [comment]
FYI these 75 commits include a _highly experimental option_ of books being located within *some separate PATH* on the filesystem...

- https://github.com/janeczku/calibre-web/issues/1462#issuecomment-1947640467

**Comment by EMG70** [comment]
IIAB-DIAGNOSTICS -http://sprunge.us/m4Dr2C?en
Video urls clickable and progress showing OK until download completed.
Screenshot from 2024-02-16 09-30-28

Screenshot from 2024-02-16 09-31-05


Please see rows 6&7 failed downloads in first tasks screenshot above .I tried to download a playlist https://www.youtube.com/watch?v=bBC-nXj3Ng4&list=PLZHQObOWTQDN52m7Y21ePrTbvXkPaWVSg&index=8 and then individual video https://www.youtube.com/watch?v=WUvTyaaNkzM&list=PLZHQObOWTQDN52m7Y21ePrTbvXkPaWVSg&index=11 immediately after a successful download.This resulted in  "failed,NonType,object is not subscriptable."

I then tried another video https://www.youtube.com/watch?v=iFK_pcrpBhY after the two failed attempts,this was successfully downloaded together with the previously failed videos.

I am trying again to see if this can be replicated or it was just a glitch in the network.

**Comment by nzola** [comment]
Upgraded Calibre-web on iiab Rpi4 witho
image
ut any problems. Downloaded successfully a complete videos playlist,

**Comment by nzola** [comment]
Reinstalled Multipass on my laptop without any problems. Downloading a complete videos playlist right now, so far so good. Still going not yet completed. It is 3:51 am going to bed.


image

**Comment by deldesir** [comment]
Thanks @nzola. Happy your tests went pretty well. The 2 failed URLs are caused by a URL handling issue. I am working on it.

By the way https://www.youtube.com/@iogacademy/playlists is a playlist of playlists. Can take hours to fully download.

**Pull request merged**
