### PR TITLE
Retrieve relevant description

### PR DESCRIPTION
**Pull request by deldesir**
🚀 **Pull Request Overview:**

This pull request retrieves the correct description for each video.

📋 **Checklist:**
- [x] Tested the changes thoroughly.

📌 **Testing scenarios:**
See Issue #97 

cc @EMG70

PS _This PR builds upon #110 to #114_

### CODE REVIEW

**Comment by holta** [comment]
FYI this PR patches a small functionality regression introduced by:

- PR #109

**Comment by deldesir** [comment]
Tested on LRN2:

Before (with incorrect description,  prior to applying this PR):
before

After (with correct description, after applying this PR):
after

**Comment by EMG70** [comment]
iiab-diagnostics http://sprunge.us/XPsd7T?en
Downloaded videos appear with full title in Tasks.The video url is now clickable.Good progress @deldesir .I will keep testing and update.
Screenshot from 2024-01-31 17-17-15

**Comment by EMG70** [comment]
Just to add,the first video in the playlist shows progress until 62%  and stalled ,the rest were in "waiting " status .Downloading progressed in the background until all  were successfully downloaded.

**Pull request merged**
