### PR TITLE
Refactor for better maintainability

### PR DESCRIPTION
**Pull request by deldesir**
With this PR, the metadata task code is better structured. There is no functionality added, just a refactor. This will allow top 100 feature PRs to be more organized.

### CODE REVIEW

**Comment by holta** [comment]
Clarify if this PR is tested with some of the 5 + 7 testing scenarios at... ?

- #97

(Which if so?  Thanks!)

**Comment by deldesir** [comment]
Tested with a short playlist for shelf creation and population (1 and 6)

image

image

**Comment by holta** [comment]
> Tested with a short playlist for shelf creation and population (1 and 6)

Do you mean the NEW Testing Scenarios 1 and 6 at... ?

- https://github.com/iiab/calibre-web/issues/97#issuecomment-2021756659

(And if so, are the OLDER Testing Scenarios 1-to-5 at the top of #79 sufficiently tested/safe here?)

**Comment by deldesir** [comment]
Yes, I mean the new testing scenarios. I smoke tested this PR for existing functionalities. No regression introduced, no feature added. I've been working on it for hours. However, if something is missed or broken, it will be addressed promptly.

**Pull request merged**
