### PR TITLE
Enable subsequent [re]downloads of playlists

### LINKED ISSUE #150: Subsequent playlists redownloads fail
IIAB-DIAGNOSTICS - http://sprunge.us/oECy1e?en
This playlist https://www.youtube.com/playlist?list=PLGjplNEQ1it_oTvuLRNqXfz_v_0pq6unW of 14 videos was downloaded successfully and videos in order of ranking.. see screenshot.

Subsequent download attempts for these below have all failed in tasks but an empty  bookshelf name is created.
https://www.youtube.com/playlist?list=PLGjplNEQ1it_oTvuLRNqXfz_v_0pq6unW  14 videos
https://www.youtube.com/playlist?list=PLfEr2kn3s-bo4LwlbyZugHPavhcdW8YMC               97 videos 
Screenshot from 2024-03-27 14-51-32
Screenshot from 2024-03-27 14-52-05
Screenshot from 2024-03-27 14-55-11
Screenshot from 2024-03-27 15-03-21

_Originally posted by @EMG70 in https://github.com/iiab/calibre-web/issues/146#issuecomment-2023012983_

### PR DESCRIPTION
**Pull request by deldesir**
Fixes #150. This PR adds a timestamp to playlists' paths after they are downloaded.

[ 2024-05-30 SUMMARY: xklb generally does not support subsequent redownloading of playlists, so let's try this workaround! ]

### CODE REVIEW

**Comment by deldesir** [comment]
Tested with subsequent [re]downloading of a small playlist. Couldn't test with long playlists due to potential disk IO error.

image

**Comment by EMG70** [comment]
IIAB-DIAGNOSTICS  - http://sprunge.us/SormHj?en

All single single videos and playlists failing to download.

https://www.youtube.com/watch?v=T3kDWpREiEI&list=PLoC8Q0moRTSjKkMZoVkAgHMJjkpUreleb&index=21e - single video
https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi - 102 short videos in playlist
https://www.youtube.com/playlist?list=PLr6-GrHUlVf96NLj3PQq-tmEB6woZjwEl - 53 short videos in playlist

Screenshot from 2024-03-28 18-03-17

**Comment by holta** [comment]
> Hi @EMG70. Reading your log, it looks like xklb-metadata.db is missing. Can you check by doing `ls /library/calibre-web/xklb-metadata.db` using your terminal?

Or run this as root...

```
apt install tree
cd /library/calibre-web
tree
```

**Comment by EMG70** [comment]
> Hi @EMG70. Reading your log, it looks like xklb-metadata.db is missing. Can you check by doing `ls /library/calibre-web/xklb-metadata.db` using your terminal?
Here is the output
Screenshot from 2024-03-28 18-31-47

**Comment by deldesir** [comment]
Line 1090 in your log says you don't have XKLB installed

**Comment by deldesir** [comment]
To confirm run:
```which lb```

If it is found, do 

```
lb --version
```

**Comment by deldesir** [comment]
Please go ahead, no worry.

**Comment by EMG70** [comment]
> To confirm run: `which lb`
> 
> If it is found, do
> 
> ```
> lb --version
> ```

sorry a bit late now,VM destroyed.

**Comment by EMG70** [comment]
Please check if all is ok before proceeding with testing.

image

**Comment by deldesir** [comment]
Looks good so far

**Comment by holta** [comment]
Plz post ideas(s) as to why the earlier XKLB install failed / disappeared, if possible?

**Comment by EMG70** [comment]
IIAB-DIAGNOSTICS - http://sprunge.us/tjeC5u?en

Downloading and video ranking showing OK .Subsequent playlist downloads all failed no matter number of videos in playlist,however a single video downloads well.
IMG_3162

This playlist downloaded  all 53 videos ok  but failed on second attempt. https://www.youtube.com/playlist?list=PLr6-GrHUlVf96NLj3PQq-tmEB6woZjwEl
https://www.youtube.com/playlist?list=PLiMWaCMwGJXlQj0BFEwew0fvhOPr833GS 7 videos fails

**Comment by deldesir** [comment]
I cannot reproduce your issue @EMG70, sorry. Both URLs work for me all videos downloaded, except 1 (https://www.youtube.com/watch?v=7m4_kZOObzw). I am afraid you might be subject to some limitations either by your ISP or YouTube itself

**Comment by EMG70** [comment]
You could be right.I have not done any testing since I changed ISP two weeks ago.
I will try and see what's going on.

**Comment by holta** [comment]
> might be subject to some limitations either by your ISP or YouTube itself

We can and should arrange for @EMG70[*] to do the exact same test remotely (i.e. with a different ISP and different YouTube geographic restrictions) to confirm what exactly is happening and why.

[*] And others too, if possible!

@deldesir can you help spell out the exact steps of what most needs to be tested, to help everyone avoid ambiguity here?

**Comment by deldesir** [comment]
We're dealing with a download issue. We know we have a successful test if we provide 2-3 playlists one after the other and the following conditions are met for them:
- metadata are fetched and total duration is displayed
- videos are downloaded (a few failures are ok)
- shelves are created and populated

**Comment by holta** [comment]
> We know we have a successful test if we provide 2-3 playlists one after the other and the following conditions are met [,,,]

Thanks for explaining.

Are we also trying to test: repeatedly entering the same playlist URL?

(i.e. clicking "Download to IIAB" each time, and entering the same YouTube playlist URL each time, a few times in succession)

**Comment by deldesir** [comment]
Yes to ensure redownloading is not an issue.

**Comment by EMG70** [comment]
Another test was done on @holta  VM (t5)  via VPN.The downloads also failed but with different output compared to my new VM's output.
screenshots from t5 VM below:
https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi - 102 short videos in playlist
https://www.youtube.com/playlist?list=PLr6-GrHUlVf96NLj3PQq-tmEB6woZjwEl - 53 short videos in playlist
Screenshot 2024-03-29 052023
Screenshot 2024-03-29 052134

**Comment by holta** [comment]
Huge thanks @EMG70:

> downloads also failed but with different output compared to my new VM

@deldesir can log into t5 here, and do your best to reproduce / analyze / explain this?

**Comment by EMG70** [comment]
A new VM was created on my machine and PR#151 updated.
IIAB-DIAGNOSTICS - http://sprunge.us/SkoORM?en
https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi - 102 short videos in playlist
https://www.youtube.com/playlist?list=PLr6-GrHUlVf96NLj3PQq-tmEB6woZjwEl - 53 short videos in playlist

Screenshot from 2024-03-29 05-41-50

**Comment by holta** [comment]
> A new VM was created on my machine and PR#151 updated.

XKLB failed to install once again?  See below Line 1126 here:
https://sprunge.us/SkoORM?en#n-1126

_@EMG70 please run `pastebinit -b sprunge.us /opt/pipx/logs/*` and reply with the sprunge.us URL, Thank You!_

image

These 2 pages might also shed light?

- https://pipx.pypa.io/stable/troubleshooting/
- https://github.com/iiab/calibre-web/wiki#xklb-and-yt-dlp-back-end-integration

**Comment by deldesir** [comment]
Looking into t5...

**Comment by EMG70** [comment]
IIAB-DIAGNOSTICS - http://sprunge.us/Kv2wBX?en
https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi - 102 short videos in playlist ✅
https://www.youtube.com/playlist?list=PLr6-GrHUlVf96NLj3PQq-tmEB6woZjwEl - 53 short videos in playlist ✅
100/102 Videos were downloaded OK.Two videos failed https://www.youtube.com/watch?v=4e3dIeP93E8 and https://www.youtube.com/watch?v=D2KvDBSZA0w although they do play well on Youtube.I am not sure why,see screenshot below
Screenshot from 2024-04-09 14-55-18

**Comment by EMG70** [comment]
Sorry did i post on wrong PR.I have just posted same on PR#150

**Comment by EMG70** [comment]
> Thanks a lot for testing again. The UNIQUE constraint error is a database issue. I'll let you know more once I am done examining your log.

IIAB-DIAGNOSTICS - http://sprunge.us/Kv2wBX?en
https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi - 102 short videos in playlist ✅
https://www.youtube.com/playlist?list=PLr6-GrHUlVf96NLj3PQq-tmEB6woZjwEl - 53 short videos in playlist ✅
97/102 Videos were downloaded OK.A few videos failed https://www.youtube.com/watch?v=4e3dIeP93E8 and https://www.youtube.com/watch?v=D2KvDBSZA0w although they do play well on Youtube.I am not sure why,see screenshots:
Screenshot from 2024-04-09 14-31-01
Screenshot from 2024-04-09 14-55-18
Screenshot from 2024-04-09 15-03-05
Screenshot from 2024-04-09 15-03-36

**Comment by deldesir** [comment]
For te 102 videos url (https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi - 102 short videos in playlist) I also had 3 failed videos:
 - https://www.youtube.com/watch?v=dIu_C5Akino
 - https://www.youtube.com/watch?v=EQCUdCG-eAA
 - https://www.youtube.com/watch?v=4e3dIeP93E8
 
 We have one in common: https://www.youtube.com/watch?v=4e3dIeP93E8
 When I forced its redownload I got the UNIQUE constraint failed: media.path error. It's because :
   1- no error was reported by xklb for the failed video. It's like the video succeeded and even got a download/local "path"
   2- since the video really failed, calibre-web did not have it, so no timestamp was added to the path

image

**Comment by holta** [comment]
Thanks @deldesir for explaining the progress:

Is targeted testing needed (e.g. from @EMG70) in coming days?

**Comment by deldesir** [comment]
Redownloading a playlist twice still doesn't work as expected.

**Comment by deldesir** [comment]
@EMG70 and @holta, I just got 100% success downloading and redownloading https://www.youtube.com/playlist?list=PL_c9BZzLwBRLVh9OdCBYFEql6esA6aRsi. What changed? No code additions, I only updated my branches based on iiab:master. I also notice the VM where failures from redownloading happened did not have this commit https://github.com/iiab/calibre-web/pull/151/commits/d9e4fc4bac4a49fd4336d3a529c57c2c246ffa0f. Examining the xklb-metada.db confirmed this because the downloaded playlist do not have any timestamps added to them.

**Comment by holta** [comment]
@deldesir what do you suggest?

**Comment by deldesir** [comment]
I'd like a second look into this. I want to be sure this works for @EMG70 too.

**Comment by holta** [comment]
Thanks @deldesir:

Please make a recommendation if additional testing is required?

**Comment by deldesir** [comment]
A clean VM @holta.
@EMG70, If you plan to test this again, ensure you don't include #152. I don't understand yet what went wrong so a clean VM with only #151 is recommended. I have to acknowledge we benefit from the enhancements made recently to [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.04.09) and [xklb](https://github.com/chapmanjacobd/library/compare/v2.5.027...v2.6.009) so your test will probably use:
- yt-dlp 2024.04.09
- xklb 2.6.009

**Comment by EMG70** [comment]
I will test tomorrow and update you.

**Comment by deldesir** [comment]
@EMG70 and @holta, downloading channel with this PR is not solid yet due to "Shorts" not having time_uploaded. I'll let you know once I'm done handling this in a better way. For your tests, please consider playlists only for now.

**Comment by EMG70** [comment]
IIAB-DIAGNOSTICS -  http://sprunge.us/Rf3QgC?en

Screenshot from 2024-04-16 20-36-29
There were two failed videos ,one of them is 9hrs,not sure why the content creator included it as part of a playlist JavaScript Programming All-in-One Tutorial Series (9 HOURS!) https://www.youtube.com/watch?v=9M4XKi25I2M .
This probably explains why Task output seemed to be hung (failed to download:download appears to be stuck)

The second video  that failed https://www.youtube.com/watch?v=NBRdd18N5X0  was also tried individually and still returned a failed output in Task ( failed to download:UNIQUE constraint failed.media.path).
Screenshot from 2024-04-16 20-47-13

**Comment by deldesir** [comment]
Happy this is getting more robust. Thanks @EMG70. 

The UNIQUE constraint failed.media.path is not difficult to tackle. It's because the stuck videos are not post-timestamped. I'm thinking of the best way to fix it.

**Comment by holta** [comment]
@EMG70 we're hoping a quick test with YouTube Shorts (@deldesir will help) confirms this PR can be merged quickly, ideally today!

**Comment by holta** [comment]
This PR was tested with #155 and #157 on t4 as explained here:

- https://github.com/iiab/calibre-web/pull/157#issuecomment-2142393561

@deldesir confirms that #151 is ready to go.

**Pull request merged**
